version = 1
SPDX-PackageName = "spotdesirability"
SPDX-PackageSupplier = "bartzbeielstein <32470350+bartzbeielstein@users.noreply.github.com>"
SPDX-PackageDownloadLocation = "https://github.com/sequential-parameter-optimization/spotdesirability"

[[annotations]]
path = [".gitignore", ".releaserc.json", ".vscode/settings.json", "makefile.sh", "pyproject.toml", "uv.lock", "tox.ini", "_quarto.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = [".github/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["*.md", "*.qmd", "docs/**", "reference/**", "objects.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "logo/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "img/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "scripts/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "tests/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "src/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["**/__pycache__/**", ".pytest_cache/**", "site/**", "dist/**", "_site/**", "_inv/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "GPL-2.0-or-later"
